-- V1: Baseline legacy fixes
--
-- Runs against BOTH existing databases (created by old Hibernate ddl-auto=update)
-- AND fresh databases. All statements use IF EXISTS / IF NOT EXISTS, so on a fresh
-- database they no-op and Hibernate creates the tables from the entity classes.

-- ---- Columns that Hibernate ddl-auto=update may have missed historically ----
ALTER TABLE IF EXISTS KEY_IDEAS ADD COLUMN IF NOT EXISTS TAGS VARCHAR(500);
ALTER TABLE IF EXISTS KEY_IDEAS ADD COLUMN IF NOT EXISTS HIGHLIGHTED BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS EXCERPTS  ADD COLUMN IF NOT EXISTS HIGHLIGHTED BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS BOOKS     ADD COLUMN IF NOT EXISTS RATING INTEGER DEFAULT NULL;
ALTER TABLE IF EXISTS BOOKS     ADD COLUMN IF NOT EXISTS CHAPTER_IMAGES_ENABLED BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS BOOKS     ADD COLUMN IF NOT EXISTS CATEGORY VARCHAR(255) DEFAULT NULL;
ALTER TABLE IF EXISTS BOOKS     ADD COLUMN IF NOT EXISTS READING_STATUS VARCHAR(50) DEFAULT NULL;
ALTER TABLE IF EXISTS BOOKS     ADD COLUMN IF NOT EXISTS START_DATE DATE DEFAULT NULL;
ALTER TABLE IF EXISTS BOOKS     ADD COLUMN IF NOT EXISTS FINISH_DATE DATE DEFAULT NULL;

-- ---- Drop legacy @OneToOne unique constraint on BOOK_REVIEWS.book_id ----
-- The old @OneToOne mapping created a UNIQUE INDEX on BOOK_ID which H2 reused as
-- the supporting index for the FK to BOOKS. Drop the FK first, then the index,
-- then re-add a plain FK. Names harvested from the original auto-generated schema.
ALTER TABLE IF EXISTS BOOK_REVIEWS DROP CONSTRAINT IF EXISTS "FKCM2SHIVX19SPBG0FLC47MCRS1";
DROP INDEX IF EXISTS UK_DDVGQX2QY2GEBIBQF3Q02C3HG_INDEX_B;
ALTER TABLE IF EXISTS BOOK_REVIEWS
    ADD CONSTRAINT IF NOT EXISTS FK_BOOK_REVIEWS_BOOK
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID);
