-- V3: Per-chapter AI "explanation" (详解) documents.
--
-- Idempotent like V1/V2: uses IF NOT EXISTS so it no-ops on databases where
-- Hibernate ddl-auto=update already created the table, and applies cleanly on
-- databases that do not have it yet.

CREATE TABLE IF NOT EXISTS CHAPTER_EXPLANATIONS (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CHAPTER_ID BIGINT NOT NULL UNIQUE,
    CONTENT CLOB,
    UPDATED_AT DATE,
    CONSTRAINT FK_CHAPTER_EXPLANATION_CHAPTER FOREIGN KEY (CHAPTER_ID) REFERENCES CHAPTERS(ID)
);
