-- V5: Book collections (file-system-like folders) + many-to-many book membership.
--
-- Idempotent (IF NOT EXISTS) so it no-ops where Hibernate ddl-auto=update already
-- created the structures, and applies cleanly on databases that lack them.

CREATE TABLE IF NOT EXISTS BOOK_COLLECTIONS (
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    PARENT_ID  BIGINT DEFAULT NULL,
    NAME       VARCHAR(200) NOT NULL,
    SORT_ORDER INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BOOK_COLLECTION_ITEMS (
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    COLLECTION_ID BIGINT NOT NULL,
    BOOK_ID       BIGINT NOT NULL,
    ADDED_AT      TIMESTAMP,
    CONSTRAINT UK_BOOK_COLLECTION_ITEMS UNIQUE (COLLECTION_ID, BOOK_ID)
);

CREATE INDEX IF NOT EXISTS IDX_BCI_COLLECTION_ID ON BOOK_COLLECTION_ITEMS (COLLECTION_ID);
CREATE INDEX IF NOT EXISTS IDX_BCI_BOOK_ID ON BOOK_COLLECTION_ITEMS (BOOK_ID);
