-- V6: Manual reading bookmarks on chapter explanations ("I read up to here").
--
-- Idempotent like earlier migrations: IF NOT EXISTS lets this no-op on databases
-- where Hibernate ddl-auto=update already created the table, while still applying
-- cleanly on databases that do not have it yet.

CREATE TABLE IF NOT EXISTS READING_BOOKMARKS (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BOOK_ID BIGINT NOT NULL,
    CHAPTER_ID BIGINT NOT NULL,
    SCROLL_RATIO DOUBLE,
    NOTE VARCHAR(500),
    CREATED_AT TIMESTAMP,
    CONSTRAINT FK_READING_BOOKMARK_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID),
    CONSTRAINT FK_READING_BOOKMARK_CHAPTER FOREIGN KEY (CHAPTER_ID) REFERENCES CHAPTERS(ID)
);

CREATE INDEX IF NOT EXISTS IDX_READING_BOOKMARK_BOOK ON READING_BOOKMARKS(BOOK_ID);
