-- Safe idempotent migrations: add new columns that Hibernate ddl-auto=update may miss
ALTER TABLE KEY_IDEAS ADD COLUMN IF NOT EXISTS TAGS VARCHAR(500);
ALTER TABLE KEY_IDEAS ADD COLUMN IF NOT EXISTS HIGHLIGHTED BOOLEAN DEFAULT FALSE;
ALTER TABLE EXCERPTS ADD COLUMN IF NOT EXISTS HIGHLIGHTED BOOLEAN DEFAULT FALSE;
ALTER TABLE BOOKS ADD COLUMN IF NOT EXISTS RATING INTEGER DEFAULT NULL;
ALTER TABLE BOOKS ADD COLUMN IF NOT EXISTS CHAPTER_IMAGES_ENABLED BOOLEAN DEFAULT FALSE;
ALTER TABLE BOOKS ADD COLUMN IF NOT EXISTS CATEGORY VARCHAR(255) DEFAULT NULL;
ALTER TABLE BOOKS ADD COLUMN IF NOT EXISTS READING_STATUS VARCHAR(50) DEFAULT NULL;
ALTER TABLE BOOKS ADD COLUMN IF NOT EXISTS START_DATE DATE DEFAULT NULL;
ALTER TABLE BOOKS ADD COLUMN IF NOT EXISTS FINISH_DATE DATE DEFAULT NULL;

-- Note: the legacy UNIQUE index on book_reviews.book_id is dropped at runtime by
-- BookReviewSchemaMigration.java (it needs to drop a dependent FK first, then re-add it).
